# Generated by Django 4.2.1 on 2023-05-14 08:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Probe',
            fields=[
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название теста')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Описание')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('order', models.IntegerField(default=1, verbose_name='Порядок')),
                ('enabled', models.BooleanField(default=True, verbose_name='Включен для клиента')),
                ('probeSpecial', models.CharField(blank=True, max_length=250, null=True, verbose_name='Спец.маркер')),
                ('code', models.CharField(blank=True, max_length=200, null=True, verbose_name='Код')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProbeGroup',
            fields=[
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название Группы')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Описание')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Идентификатор')),
                ('order', models.IntegerField(default=1, verbose_name='Порядок')),
            ],
        ),
        migrations.CreateModel(
            name='ProbeInst',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('created', models.DateTimeField(blank=True, null=True, verbose_name='Создан')),
                ('status', models.BooleanField(default=True, verbose_name='В работе')),
                ('flag', models.BooleanField(blank=True, null=True, verbose_name='Флаг')),
                ('comment', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название теста')),
                ('probe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='probes.probe', verbose_name='Тест')),
                ('related_to_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='Привязка к анализу')),
            ],
        ),
        migrations.AddField(
            model_name='probe',
            name='related_to_probegroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='probes.probegroup', verbose_name='Привязка к группе'),
        ),
    ]
