# Generated by Django 4.2.1 on 2023-05-14 08:50

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('surname', models.CharField(max_length=200, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('fathname', models.CharField(max_length=200, verbose_name='Отчество')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Добавлен')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('dateofbirth', models.DateField(verbose_name='Дата рождения')),
                ('gender', models.CharField(choices=[('Муж', 'Муж.'), ('Жен', 'Жен.')], default='Муж', max_length=50, verbose_name='Пол')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
            ],
        ),
    ]
