# Generated by Django 4.2.1 on 2023-05-14 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('created', models.DateTimeField(verbose_name='Добавлен')),
                ('barcode', models.IntegerField(blank=True, null=True, verbose_name='Заявка')),
                ('cito', models.BooleanField(default=False, verbose_name='CITO')),
                ('notes', models.CharField(blank=True, max_length=254, null=True, verbose_name='Комментарий')),
                ('patients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient', verbose_name='Пациент')),
            ],
        ),
    ]
